# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9adb4a6a42fafa75532950902f957a620ffb9d8e49c0d8fbfd19905096406f1a8f0771b8b5fc07bb2309b8689731f27c750642adea60ac54b51f255239c58787

test:
  secret_key_base: d46d4b4a07c88ab6967af2f507e3a60dfac324093bbcd57cc5cd69ebc550ec77f1d3d46103ab3529ced97e0f0a8936ef8eb108df7d37cbcc35c4182edcb5927f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
